<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-Q9LCM9F" failures="5" tests="55" name="com.CA.qa.TestCases.APITesting" time="31.356" errors="0" timestamp="2020-12-04T19:11:59 IST" skipped="0">
  <testcase classname="com.CA.qa.TestCases.APITesting" name="API_TESTING_with_Automation" time="1.466"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.APITesting" name="API_TESTING_with_Automation" time="0.359"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.APITesting" name="API_TESTING_with_Automation" time="0.376"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.APITesting" name="API_TESTING_with_Automation" time="1.603"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.APITesting" name="API_TESTING_with_Automation" time="0.888">
    <failure message="Api not worked expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Api not worked expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at com.CA.qa.TestCases.APITesting.API_TESTING_with_Automation(APITesting.java:31)
at jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- API_TESTING_with_Automation -->
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.APITesting" name="API_TESTING_with_Automation" time="0.727"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.APITesting" name="API_TESTING_with_Automation" time="0.541"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.APITesting" name="API_TESTING_with_Automation" time="0.602"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.APITesting" name="API_TESTING_with_Automation" time="0.379"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.APITesting" name="API_TESTING_with_Automation" time="0.424"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.APITesting" name="API_TESTING_with_Automation" time="0.275"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.APITesting" name="API_TESTING_with_Automation" time="1.403">
    <failure message="Api not worked expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Api not worked expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at com.CA.qa.TestCases.APITesting.API_TESTING_with_Automation(APITesting.java:31)
at jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- API_TESTING_with_Automation -->
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.APITesting" name="API_TESTING_with_Automation" time="0.297"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.APITesting" name="API_TESTING_with_Automation" time="0.253"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.APITesting" name="API_TESTING_with_Automation" time="0.727"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.APITesting" name="API_TESTING_with_Automation" time="0.365"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.APITesting" name="API_TESTING_with_Automation" time="0.325"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.APITesting" name="API_TESTING_with_Automation" time="1.075"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.APITesting" name="API_TESTING_with_Automation" time="0.654"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.APITesting" name="API_TESTING_with_Automation" time="0.324"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.APITesting" name="API_TESTING_with_Automation" time="0.390">
    <failure message="Api not worked expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Api not worked expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at com.CA.qa.TestCases.APITesting.API_TESTING_with_Automation(APITesting.java:31)
at jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- API_TESTING_with_Automation -->
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.APITesting" name="API_TESTING_with_Automation" time="0.282"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.APITesting" name="API_TESTING_with_Automation" time="0.276"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.APITesting" name="API_TESTING_with_Automation" time="0.265"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.APITesting" name="API_TESTING_with_Automation" time="0.807"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.APITesting" name="API_TESTING_with_Automation" time="0.309">
    <failure message="Api not worked expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Api not worked expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at com.CA.qa.TestCases.APITesting.API_TESTING_with_Automation(APITesting.java:31)
at jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- API_TESTING_with_Automation -->
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.APITesting" name="API_TESTING_with_Automation" time="0.417"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.APITesting" name="API_TESTING_with_Automation" time="0.237"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.APITesting" name="API_TESTING_with_Automation" time="0.325"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.APITesting" name="API_TESTING_with_Automation" time="0.368"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.APITesting" name="API_TESTING_with_Automation" time="0.484"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.APITesting" name="API_TESTING_with_Automation" time="1.597"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.APITesting" name="API_TESTING_with_Automation" time="0.397"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.APITesting" name="API_TESTING_with_Automation" time="0.403"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.APITesting" name="API_TESTING_with_Automation" time="0.385"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.APITesting" name="API_TESTING_with_Automation" time="0.426">
    <failure message="Api not worked expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Api not worked expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at com.CA.qa.TestCases.APITesting.API_TESTING_with_Automation(APITesting.java:31)
at jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- API_TESTING_with_Automation -->
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.APITesting" name="API_TESTING_with_Automation" time="0.796"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.APITesting" name="API_TESTING_with_Automation" time="0.765"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.APITesting" name="API_TESTING_with_Automation" time="0.321"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.APITesting" name="API_TESTING_with_Automation" time="0.379"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.APITesting" name="API_TESTING_with_Automation" time="0.874"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.APITesting" name="API_TESTING_with_Automation" time="0.426"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.APITesting" name="API_TESTING_with_Automation" time="0.259"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.APITesting" name="API_TESTING_with_Automation" time="0.595"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.APITesting" name="API_TESTING_with_Automation" time="0.439"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.APITesting" name="API_TESTING_with_Automation" time="0.455"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.APITesting" name="API_TESTING_with_Automation" time="0.732"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.APITesting" name="API_TESTING_with_Automation" time="1.604"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.APITesting" name="API_TESTING_with_Automation" time="0.305"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.APITesting" name="API_TESTING_with_Automation" time="0.288"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.APITesting" name="API_TESTING_with_Automation" time="0.289"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.APITesting" name="API_TESTING_with_Automation" time="0.315"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.APITesting" name="API_TESTING_with_Automation" time="0.261"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.APITesting" name="API_TESTING_with_Automation" time="1.569"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.APITesting" name="API_TESTING_with_Automation" time="0.253"/>
  <system-out/>
</testsuite> <!-- com.CA.qa.TestCases.APITesting -->
