<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="ozonetel-santosh" failures="3" tests="59" name="com.CA.qa.TestCases.ValidateOutboundCampaignPageTest" time="200.514" errors="0" timestamp="2021-06-01T20:52:07 IST" skipped="0">
  <testcase classname="com.CA.qa.TestCases.ValidateOutboundCampaignPageTest" name="ValidateCampaignNameErrorMsg26_1" time="1.170"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateOutboundCampaignPageTest" name="ValidateCampaignNameRangeErrorMsg26_12" time="1.184"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateOutboundCampaignPageTest" name="ValidateCampaignNameDuplicateErrorMsg25_11" time="1.223"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateOutboundCampaignPageTest" name="ValidateCampaignNameSplRangeErrorMsg26_13" time="1.203"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateOutboundCampaignPageTest" name="ValidateCampaignNameSplRangeErrorMsg26_14" time="1.191"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateOutboundCampaignPageTest" name="ValidateCampaignTypeErrorMsg26_2" time="1.141"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateOutboundCampaignPageTest" name="ValidateDidErrorMsg26_3" time="1.134"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateOutboundCampaignPageTest" name="ValidateDidRangeErrorMsg26_31" time="1.202"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateOutboundCampaignPageTest" name="ValidateDidRangeErrorMsg26_32" time="1.176"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateOutboundCampaignPageTest" name="ValidateDidRangeErrorMsg26_33" time="1.193"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateOutboundCampaignPageTest" name="ValidateDidRangeErrorMsg26_34" time="1.193"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateOutboundCampaignPageTest" name="ValidateDidRangeMaxErrorMsg" time="1.198"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateOutboundCampaignPageTest" name="ValidateFallbackDidRangeMaxErrorMsg26_4" time="1.233"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateOutboundCampaignPageTest" name="ValidateFallbackDidRangeMaxErrorMsg26_41" time="1.196"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateOutboundCampaignPageTest" name="ValidateFallbackDidRangeMaxErrorMsg26_42" time="1.207"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateOutboundCampaignPageTest" name="ValidateFallbackDidRangeMaxErrorMsg26_43" time="1.212"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateOutboundCampaignPageTest" name="ValidateStartTimeErrorMsg26_5" time="1.112"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateOutboundCampaignPageTest" name="ValidateEndTimeErrorMsg26_51" time="1.122"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateOutboundCampaignPageTest" name="ValidateGreaterEndTimeErrorMsg26_52" time="1.351"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateOutboundCampaignPageTest" name="ValidatePriorityErrorMsg26_6" time="1.105"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateOutboundCampaignPageTest" name="ValidatePriorityRangeErrorMsg26_61" time="1.236"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateOutboundCampaignPageTest" name="ValidatePrefixRangeErrorMsg26_7" time="1.228"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateOutboundCampaignPageTest" name="ValidatePrefixRangeErrorMsg26_71" time="1.252"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateOutboundCampaignPageTest" name="ValidatePrefixRangeErrorMsg26_72" time="1.229"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateOutboundCampaignPageTest" name="ValidatePluginNameErrorMsg" time="1.269"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateOutboundCampaignPageTest" name="ValidateTriesErrorMsg26_8" time="1.110"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateOutboundCampaignPageTest" name="ValidateTriesRangeErrorMsg26_81" time="1.238"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateOutboundCampaignPageTest" name="ValidateTriesRangemaxErrorMsg26_82" time="1.219"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateOutboundCampaignPageTest" name="ValidateBlockNoEmptyErrorMsg26_9" time="1.242"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateOutboundCampaignPageTest" name="ValidateWrapupErrorMsg26_10" time="1.110"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateOutboundCampaignPageTest" name="ValidateDispositionErrorMsg26_111" time="1.150"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateOutboundCampaignPageTest" name="ValidateSkillErrorMsg26_121" time="1.110"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateOutboundCampaignPageTest" name="ValidateMapErrorMsg26_131" time="1.117"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateOutboundCampaignPageTest" name="ValidateUploadErrorMsg26_141" time="1.116"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateOutboundCampaignPageTest" name="ValidateCustomerRingTimeEmptyErrorMsg26_151" time="1.254"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateOutboundCampaignPageTest" name="ValidateCustomerRingTimeRangeErrorMsg26_152" time="1.315"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateOutboundCampaignPageTest" name="ValidateCustomerRingTimeRangeMaxErrorMsg26_153" time="1.315"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateOutboundCampaignPageTest" name="ValidateAppUrlEmptyErrorMsg26_16_1" time="1.232"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateOutboundCampaignPageTest" name="ValidateAppUrlInvalidErrorMsg26_16_2" time="1.315"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateOutboundCampaignPageTest" name="ValidateConcurrentCallsEmptyErrorMsg26_17_1" time="1.205"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateOutboundCampaignPageTest" name="ValidateConcurrentCallsRangeErrorMsg26_17_2" time="1.315">
    <failure message="expected [Max Concurrent Calls should be between 1 and 9999.] but found [Max Concurrent Calls should be between 1 and 99.]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Max Concurrent Calls should be between 1 and 9999.] but found [Max Concurrent Calls should be between 1 and 99.]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.CA.qa.TestCases.ValidateOutboundCampaignPageTest.ValidateConcurrentCallsRangeErrorMsg26_17_2(ValidateOutboundCampaignPageTest.java:439)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- ValidateConcurrentCallsRangeErrorMsg26_17_2 -->
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateOutboundCampaignPageTest" name="ValidatePacingRatioEmptyErrorMsg26_18_1" time="4.334"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateOutboundCampaignPageTest" name="ValidatePacingRatioInvalidErrorMsg26_18_2" time="1.329"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateOutboundCampaignPageTest" name="ValidatePacingRatioInvalidErrorMsg26_18_3" time="1.274"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateOutboundCampaignPageTest" name="ValidatePacingRatioInvalidErrorMsg26_18_4" time="1.279"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateOutboundCampaignPageTest" name="ValidatePacingRatioInvalidErrorMsg26_18_5" time="1.308"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateOutboundCampaignPageTest" name="ValidateMaxDropRatioEmptyErrorMsg26_19_1" time="1.207"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateOutboundCampaignPageTest" name="ValidateMaxDropRatioRangeErrorMsg26_19_2" time="1.277"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateOutboundCampaignPageTest" name="ValidateDialIntervalErrorMsg26_201" time="1.235"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateOutboundCampaignPageTest" name="ValidateEmptyMapNameErrorMsg26_202" time="21.321"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateOutboundCampaignPageTest" name="ValidateMapNameRangeErrorMsg26_203" time="31.409">
    <failure message="expected [Map Name should be between 2 to 50 alphanumeric characters long and allows special characters like _] but found [Map Name allows alphanumeric characters with Underscore]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Map Name should be between 2 to 50 alphanumeric characters long and allows special characters like _] but found [Map Name allows alphanumeric characters with Underscore]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.CA.qa.TestCases.ValidateOutboundCampaignPageTest.ValidateMapNameRangeErrorMsg26_203(ValidateOutboundCampaignPageTest.java:550)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- ValidateMapNameRangeErrorMsg26_203 -->
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateOutboundCampaignPageTest" name="ValidateMapNameSplRangeErrorMsg26_204" time="31.382">
    <failure message="expected [Map Name should be between 2 to 50 alphanumeric characters long and allows special characters like _] but found [Map Name allows alphanumeric characters with Underscore]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Map Name should be between 2 to 50 alphanumeric characters long and allows special characters like _] but found [Map Name allows alphanumeric characters with Underscore]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.CA.qa.TestCases.ValidateOutboundCampaignPageTest.ValidateMapNameSplRangeErrorMsg26_204(ValidateOutboundCampaignPageTest.java:561)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- ValidateMapNameSplRangeErrorMsg26_204 -->
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateOutboundCampaignPageTest" name="ValidateMapFileErrorMsg26_205" time="21.258"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateOutboundCampaignPageTest" name="ValidateMapFileSampleTooltipMsg26_206" time="11.189"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateOutboundCampaignPageTest" name="ValidateMapFileXlsOnlyTooltipMsg26_207" time="11.198"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateOutboundCampaignPageTest" name="ValidateFileUploadSampleTooltipMsg26_208" time="0.023"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateOutboundCampaignPageTest" name="ValidateFileUploadXlsOnlyTooltipMsg26_209" time="0.017"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateOutboundCampaignPageTest" name="ValidateMappingTooltipMsg26_210" time="0.016"/>
  <system-out/>
  <testcase classname="com.CA.qa.TestCases.ValidateOutboundCampaignPageTest" name="ValidateConsolidatedErrMsg" time="10.135"/>
  <system-out/>
</testsuite> <!-- com.CA.qa.TestCases.ValidateOutboundCampaignPageTest -->
